version: 0.2

phases:
  install:
    commands:
    - npm install --silent --progress=false -g npm
    - npm install --silent --progress=false -g serverless
    - npm install --silent --progress-false
    - npm --version
  pre-build:
    commands:
    - mkdir -p ../github.com/korest/WaitlistAppAuthLambdas
    - mv * ../github.com/korest/WaitlistAppAuthLambdas
    - mv ../github.com .
    - cd github.com/korest/WaitlistAppAuthLambdas
  build:
    commands:
    - make deploy
  post_build:
    commands:
    - echo Build completed on `date`